version: '3'
services:
    app:
        container_name: app
        build:
            dockerfile: ./docker/php/DockerFile
        volumes: 
            - /var/www/html/vendor
            - ./app:/var/www/html
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
        networks:
            - web_php
        extra_hosts:
            # Ensure that host.docker.internal is correctly defined on Linux
            - host.docker.internal:host-gateway
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            REDIST_HOST: ${REDIST_HOST}
            REDIST_PORT: ${REDIST_PORT}
            # See https://xdebug.org/docs/all_settings#mode
            XDEBUG_MODE: "${XDEBUG_MODE:-off}"

    web:
        container_name: nginx
        build:
            dockerfile: ./docker/nginx/DockerFile
        ports:
            - '80:80'
        volumes: 
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - web_php
            
    mariadb:
        container_name: mariadb
        image: 'mariadb:10'
        ports:
            - '3306:3306'
        restart: unless-stopped
        volumes:
            - mariadbdata:/var/lib/mysql
        networks:
            - web_php
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

    #redis
    # cache:
    #     container_name: redis
    #     image: redis:latest
    #     networks:
    #         - web_php
    
volumes:
    mariadbdata:

networks:
    web_php:
        driver: bridge